### ISSUE TITLE
Issues with "storageClassName"

### ISSUE THREAD

**Issue by joekr** [amithkk/stable-diffusion-k8s#1]
[values.yaml](https://github.com/amithkk/stable-diffusion-k8s/blob/master/charts/stable-diffusion/values.yaml#L27) calls out 
> # If defined, storageClassName: <storageClass>
which isn't working when I set `storageClassName` in my local copy of values.yaml.

but looking at [statefulset.yaml](https://github.com/amithkk/stable-diffusion-k8s/blob/4bf7672e13c8749d7d79fb353c9b9132f16cbb7e/charts/stable-diffusion/templates/statefulset.yaml#L22) it looks like it should be `storageClass`. Using `storageClass` I can see my PVC has the expected value in the `STORAGECLASS` column.

**Comment by amithkk** [comment]
Thank you for reporting this! I will update the values.yaml to match
